POST https://localhost:7041/api/product/create HTTP/1.1
Content-Type: application/json

{
  "productId": "3f060547-80e2-4650-89b8-c63a3a7bde79",
  "productName": "Test_Product1",
  "productYear": 2022,
  "channelId": 1,
  "sizeScaleId": "58b7d976-d37e-3b16-8477-fd942752bbcf",
  "articles": [
    {
      "ArticleId": "d6473e71-462f-4793-a735-4362c646eb9f",
      "ColourId": "4b1943d7-480f-3c32-aa18-35b335604fbe"
    }
  ]
}
